# Generated by Django 4.1.5 on 2023-01-27 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ad5a90c7-d7df-415d-b383-2808be659b78'), editable=False, primary_key=True, serialize=False),
        ),
    ]
